import { ProductCategory, ProductSubcategory } from '@prisma/client';

/** Canonical subcategory catalog (Prisma enum) keyed by ProductCategory. */
export const SUBCATEGORIES_BY_CATEGORY: Record<ProductCategory, ProductSubcategory[]> = {
  STANDOFF_2: ['STANDOFF_GOLD', 'STANDOFF_ACCOUNTS', 'STANDOFF_SKINS', 'STANDOFF_OTHER'],
  STEAM: ['STEAM_TOPUP', 'STEAM_ACCOUNTS', 'STEAM_KEYS', 'STEAM_SKINS', 'STEAM_OTHER'],
  ROBLOX: ['ROBLOX_ROBUX', 'ROBLOX_ACCOUNTS', 'ROBLOX_ITEMS', 'ROBLOX_OTHER'],
  RP_PROJECTS: ['RP_VIRTS', 'RP_ACCOUNTS', 'RP_ITEMS', 'RP_OTHER'],
  BRAWL_STARS: ['BRAWL_DONATE', 'BRAWL_ACCOUNTS', 'BRAWL_BOOST', 'BRAWL_OTHER'],
  CS2: ['CS2_SKINS', 'CS2_ACCOUNTS', 'CS2_BOOST', 'CS2_OTHER'],
  FORTNITE: ['FORTNITE_DONATE', 'FORTNITE_ACCOUNTS', 'FORTNITE_SERVICES', 'FORTNITE_OTHER'],
  VALORANT: ['VALORANT_DONATE', 'VALORANT_ACCOUNTS', 'VALORANT_SERVICES', 'VALORANT_OTHER'],
  GTA_5: ['GTA5_DONATE', 'GTA5_CURRENCY', 'GTA5_ACCOUNTS', 'GTA5_SERVICES', 'GTA5_OTHER'],
  GTA_6: ['GTA6_ACCOUNTS', 'GTA6_KEYS'],
  DOTA_2: ['DOTA_ACCOUNTS', 'DOTA_ITEMS', 'DOTA_BOOST', 'DOTA_OTHER'],
  PUBG_MOBILE: ['PUBG_DONATE', 'PUBG_ACCOUNTS', 'PUBG_SERVICES', 'PUBG_OTHER'],
  GENSHIN: ['GENSHIN_DONATE', 'GENSHIN_ACCOUNTS', 'GENSHIN_SERVICES', 'GENSHIN_OTHER'],
  MOBILE_LEGENDS: ['ML_DONATE', 'ML_ACCOUNTS', 'ML_SERVICES', 'ML_OTHER'],
  APP_STORE: ['APPSTORE_TOPUP', 'APPSTORE_GIFTCARDS', 'APPSTORE_ACCOUNTS', 'APPSTORE_OTHER'],
  PUBG: ['PUBG_DONATE', 'PUBG_ACCOUNTS', 'PUBG_SERVICES', 'PUBG_OTHER'],
  MINECRAFT: ['MC_ACCOUNTS', 'MC_ITEMS', 'MC_SERVICES', 'MC_OTHER'],
  PLAYSTATION: ['PS_ACCOUNTS', 'PS_GAMES', 'PS_TOPUP', 'PS_OTHER'],
  STALCRAFT: ['STALCRAFT_ACCOUNTS', 'STALCRAFT_ITEMS', 'STALCRAFT_SERVICES', 'STALCRAFT_OTHER'],
  PATH_OF_EXILE_2: ['POE2_ACCOUNTS', 'POE2_CURRENCY', 'POE2_ITEMS', 'POE2_OTHER'],
  OTHER: ['OTHER_ACCOUNTS', 'OTHER_ITEMS', 'OTHER_BOOST', 'OTHER_MISC'],
};

export function assertSubcategoryForCategory(
  category: ProductCategory,
  subcategory: ProductSubcategory | null | undefined,
): void {
  if (!subcategory) return;
  const allowed = SUBCATEGORIES_BY_CATEGORY[category];
  if (!allowed.includes(subcategory)) {
    throw new Error(`Подкатегория ${subcategory} недоступна для категории ${category}.`);
  }
}
