-- AlterEnum ProductCategory
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'CS2';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'FORTNITE';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'VALORANT';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'GTA_5';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'GTA_6';

-- AlterEnum ProductSubcategory
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'CS2_SKINS';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'CS2_ACCOUNTS';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'CS2_BOOST';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'CS2_OTHER';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'FORTNITE_DONATE';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'FORTNITE_ACCOUNTS';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'FORTNITE_SERVICES';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'FORTNITE_OTHER';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'VALORANT_DONATE';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'VALORANT_ACCOUNTS';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'VALORANT_SERVICES';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'VALORANT_OTHER';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'GTA5_DONATE';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'GTA5_CURRENCY';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'GTA5_ACCOUNTS';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'GTA5_SERVICES';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'GTA5_OTHER';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'GTA6_ACCOUNTS';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'GTA6_KEYS';
