CREATE TYPE "BanReason" AS ENUM ('MISCONDUCT', 'THIRD_PARTY_ADS', 'OFF_PLATFORM_DEAL', 'FRAUD', 'OTHER');
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "banReason" "BanReason";
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "banComment" VARCHAR(1000);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bannedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bannedUntil" TIMESTAMP(3);
