/** Category cover images served from /public/categories (160×160 WebP). */
export const CATEGORY_IMAGES: Record<string, string> = {
  STANDOFF_2: '/categories/standoff-2.webp',
  STEAM: '/categories/steam.webp',
  ROBLOX: '/categories/roblox.webp',
  BRAWL_STARS: '/categories/brawl-stars.webp',
  RP_PROJECTS: '/categories/rp-projects.webp',
  CS2: '/categories/cs2.webp',
  FORTNITE: '/categories/fortnite.webp',
  VALORANT: '/categories/valorant.webp',
  GTA_5: '/categories/gta-5.webp',
  GTA_6: '/categories/gta-6.webp',
  DOTA_2: '/categories/dota-2.webp',
  PUBG_MOBILE: '/categories/pubg-mobile.webp',
  GENSHIN: '/categories/genshin.webp',
  MOBILE_LEGENDS: '/categories/mobile-legends.webp',
  APP_STORE: '/categories/app-store.webp',
  PUBG: '/categories/pubg.webp',
  MINECRAFT: '/categories/minecraft.webp',
  PLAYSTATION: '/categories/playstation.webp',
  STALCRAFT: '/categories/stalcraft.webp',
  PATH_OF_EXILE_2: '/categories/path-of-exile-2.webp',
  OTHER: '/categories/other.webp',
};
