/** Category cover images served from /public/categories */
export const CATEGORY_IMAGES: Record<string, string> = {
  STANDOFF_2: '/categories/standoff-2.png',
  STEAM: '/categories/steam.png',
  ROBLOX: '/categories/roblox.png',
  BRAWL_STARS: '/categories/brawl-stars.png',
  RP_PROJECTS: '/categories/rp-projects.png',
  CS2: '/categories/cs2.png',
  FORTNITE: '/categories/fortnite.png',
  VALORANT: '/categories/valorant.png',
  GTA_5: '/categories/gta-5.png',
  GTA_6: '/categories/gta-6.png',
  DOTA_2: '/categories/dota-2.png',
  PUBG_MOBILE: '/categories/pubg-mobile.png',
  GENSHIN: '/categories/genshin.png',
  MOBILE_LEGENDS: '/categories/mobile-legends.png',
  APP_STORE: '/categories/app-store.png',
  PUBG: '/categories/pubg.png',
  MINECRAFT: '/categories/minecraft.png',
  PLAYSTATION: '/categories/playstation.png',
  STALCRAFT: '/categories/stalcraft.png',
  PATH_OF_EXILE_2: '/categories/path-of-exile-2.png',
  OTHER: '/categories/other.png',
};
