-- AlterEnum ProductCategory
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'DOTA_2';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'PUBG_MOBILE';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'GENSHIN';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'MOBILE_LEGENDS';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'APP_STORE';

-- AlterEnum ProductSubcategory
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'DOTA_ACCOUNTS';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'DOTA_ITEMS';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'DOTA_BOOST';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'DOTA_OTHER';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'PUBG_DONATE';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'PUBG_ACCOUNTS';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'PUBG_SERVICES';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'PUBG_OTHER';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'GENSHIN_DONATE';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'GENSHIN_ACCOUNTS';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'GENSHIN_SERVICES';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'GENSHIN_OTHER';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'ML_DONATE';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'ML_ACCOUNTS';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'ML_SERVICES';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'ML_OTHER';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'APPSTORE_TOPUP';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'APPSTORE_GIFTCARDS';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'APPSTORE_ACCOUNTS';
ALTER TYPE "ProductSubcategory" ADD VALUE IF NOT EXISTS 'APPSTORE_OTHER';
